AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
  - 'sample/**/*'

# メソッドの行数が多すぎる
MethodLength:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false
