AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
  - 'sample/**/*'
  - 'test/deep_freezable_test.rb'

# メソッドの行数が多すぎる
MethodLength:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false
